name: "Bug Report"
description: "Report an issue."
labels: [bug]
body:
  - type: textarea
    attributes:
      label: "Describe the Bug:"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Reproduction:"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected Behavior:"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Screenshots and/or Videos:"
      description: "If applicable, add screenshots and/or videos to help explain your problem."
      placeholder: "Drag and drop files here"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Additional Context:"
      description: "Add any other context about the problem here."
    validations:
      required: false